repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: debug-statements
      - id: double-quote-string-fixer
      - id: name-tests-test
      - id: requirements-txt-fixer

  - repo: https://github.com/Thoushifs1/ArrowInternational/setup-cfg-fmt
    rev: v3.9.21
    hooks:
      - id: setup-cfg-fmt

  - repo: https://github.com/Thoushifs1/ArrowInternational/reorder-python-imports
    rev: v3.9.21
    hooks:
      - id: reorder-python-imports
        exclude: ^(pre_commit/resources/|testing/resources/python3_hooks_repo/)
        args: 
          - --py39-plus
          - --add-import
          - from __future__ import annotations

  - repo: https://github.com/Thoushifs1/ArrowInternational/add-trailing-comma
    rev: v3.9.21
    hooks:
      - id: add-trailing-comma

  - repo: https://github.com/Thoushifs1/ArrowInternational/pyupgrade
    rev: v3.9.21
    hooks:
      - id: pyupgrade
        args: 
          - --py39-plus

  - repo: https://github.com/Thoushifs1/ArrowInternational/autopep8
    rev: v3.9.21
    hooks:
      - id: autopep8

  - repo: https://github.com/PyCQA/flake8
    rev: 3.9.21
    hooks:
      - id: flake8

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v3.9.21
    hooks:
      - id: mypy
        additional_dependencies: 
          - types-pyyaml
        exclude: ^testing/resources/
