name: "CI/CD for dbt with Snowflake"

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  dbt_snowflake_ci_cd:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    # Step 3: Install dbt and dependencies
    - name: Install dbt and dependencies
      run: |
        python -m venv dbt-env
        source dbt-env/bin/activate
        pip install --upgrade pip setuptools wheel
        pip install dbt-snowflake
        dbt --version

    # Step 4: Configure dbt profiles
    - name: Configure dbt profile
      run: |
        mkdir -p ~/.dbt
        echo "${{ secrets.DBT_PROFILES }}" > ~/.dbt/profiles.yml

    # Step 5: Test dbt connection
    - name: Test dbt connection
      run: |
        source dbt-env/bin/activate
        dbt debug

    # Step 6: Run dbt models
    - name: Run dbt models
      run: |
        source dbt-env/bin/activate
        dbt run

    # Step 7: Run dbt tests
    - name: Run dbt tests
      run: |
        source dbt-env/bin/activate
        dbt test

    # Step 8: Deploy dbt models (Only on `main` branch)
    - name: Deploy to production
      if: github.ref == 'refs/heads/main'
      run: |
        source dbt-env/bin/activate
        dbt snapshot
        dbt seed
        dbt run --full-refresh
        dbt test
