your_profile:
  target: Feauture
  outputs:
      type: snowflake
      account: "LZ36572"
      user: "SHAIKAHAMMAD"
      role: "ACCOUNTADMIN"
      database: "ARROW_INTRNATIONAL"
      warehouse: "COMPUTE_WH"
      schema: "TEST"
      password: "ThoushifAhammad@123"
