name: Deploy to Snowflake

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: |
          docker build -t snowsql-deploy .

      - name: Run Docker Container
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
          SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
          SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}
          SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
        run: |
          docker run --rm \
            -e SNOWFLAKE_ACCOUNT="${SNOWFLAKE_ACCOUNT}" \
            -e SNOWFLAKE_USER="${SNOWFLAKE_USER}" \
            -e SNOWFLAKE_PASSWORD="${SNOWFLAKE_PASSWORD}" \
            -e SNOWFLAKE_DATABASE="${SNOWFLAKE_DATABASE}" \
            -e SNOWFLAKE_SCHEMA="${SNOWFLAKE_SCHEMA}" \
            -e SNOWFLAKE_WAREHOUSE="${SNOWFLAKE_WAREHOUSE}" \
            snowsql-deploy
