jobs:
  deploy:
    runs-on: ubuntu-latest
    container: ghcr.io/snowflakedb/snowflake-snowsql:latest
    steps:
      - name: Run Snowflake Query
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
          SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
          SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}
          SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
        run: |
          snowsql -a $SNOWFLAKE_ACCOUNT \
                  -u $SNOWFLAKE_USER \
                  -P $SNOWFLAKE_PASSWORD \
                  -d $SNOWFLAKE_DATABASE \
                  -s $SNOWFLAKE_SCHEMA \
                  -w $SNOWFLAKE_WAREHOUSE \
                  -q "SELECT CURRENT_VERSION();"
