name: Debug SnowSQL Installation

on:
  push:
    branches:
      - main

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Verify Files
        run: |
          echo "Checking if installers directory exists..."
          if [ -d "installers" ]; then
            echo "Directory exists."
          else
            echo "Error: 'installers' directory does not exist!"
            exit 1
          fi

          echo "Listing files in installers directory:"
          ls -lah installers

          echo "Checking if SnowSQL file is present..."
          if [ -f "installers/snowsql-linux_x86_64.bash" ]; then
            echo "SnowSQL file is present."
            ls -lah installers/snowsql-linux_x86_64.bash
          else
            echo "Error: SnowSQL file does not exist in 'installers' directory!"
            exit 1
          fi
