name: Debug SnowSQL Installation

on:
  push:
    branches:
      - main

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install SnowSQL
        run: |
          sudo apt update
          sudo apt install -y unzip curl

          # Verify working directory
          pwd
          ls -lah

          # Download SnowSQL package from the official Snowflake repo
          SNOWSQL_URL="https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/latest/linux_x86_64/snowsql-linux_x86_64.bash"
          curl -L -o snowsql.bash $SNOWSQL_URL

          # Debugging information
          echo "Checking if SnowSQL file is downloaded properly"
          ls -lah snowsql.bash
          file snowsql.bash

          # Check if it's a script and not an HTML file
          if grep -q "<html" snowsql.bash; then
            echo "Downloaded file is an HTML page, not the installer. Check URL!"
            cat snowsql.bash
            exit 1
          fi

          # Install SnowSQL
          chmod +x snowsql.bash
          ./snowsql.bash -- -y || { echo "Installation failed"; exit 1; }

          # Ensure SnowSQL is in the PATH
          echo "export PATH=\$PATH:/usr/local/bin" >> ~/.bashrc
          echo "export PATH=\$PATH:/usr/local/bin" >> $GITHUB_ENV
          source ~/.bashrc

          # Verify installation
          snowsql --version || { echo "SnowSQL installation failed"; exit 1; }
