name: Deploy to Snowflake

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install SnowSQL
        run: |
          sudo apt update
          sudo apt install -y unzip wget
          
          # Download SnowSQL using authenticated request
          wget --content-disposition "https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.2/linux_x86_64/snowsql-1.2.23-linux_x86_64.bash"

          # Install SnowSQL
          chmod +x snowsql-1.2.23-linux_x86_64.bash
          ./snowsql-1.2.23-linux_x86_64.bash --quiet -- -y

          # Ensure SnowSQL is in PATH
          echo "/usr/bin" >> $GITHUB_PATH
          echo "export PATH=\$PATH:/usr/bin" >> ~/.bashrc
          source ~/.bashrc
          which snowsql
          snowsql --version

      - name: Test Snowflake Connection
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
          SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
          SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}
          SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
        run: |
          snowsql -a "$SNOWFLAKE_ACCOUNT" \
                  -u "$SNOWFLAKE_USER" \
                  -P "$SNOWFLAKE_PASSWORD" \
                  -d "$SNOWFLAKE_DATABASE" \
                  -s "$SNOWFLAKE_SCHEMA" \
                  -w "$SNOWFLAKE_WAREHOUSE" \
                  -q "SELECT CURRENT_VERSION();" || { echo "Query failed"; exit 2; }

      - name: Execute SQL Script
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
          SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
          SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}
          SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
        run: |
          snowsql -a "$SNOWFLAKE_ACCOUNT" \
                  -u "$SNOWFLAKE_USER" \
                  -P "$SNOWFLAKE_PASSWORD" \
                  -d "$SNOWFLAKE_DATABASE" \
                  -s "$SNOWFLAKE_SCHEMA" \
                  -w "$SNOWFLAKE_WAREHOUSE" \
                  -f code.sql || { echo "SQL script execution failed"; exit 2; }
