name: Deploy to Snowflake

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Debug SnowSQL Download
        run: |
          ls -lah
          file snowsql-1.2.23-linux_x86_64.bash || echo "SnowSQL file not found"
          head -n 20 snowsql-1.2.23-linux_x86_64.bash || echo "Cannot read SnowSQL file"

      - name: Verify SnowSQL Installation
        run: |
          chmod +x snowsql-1.2.23-linux_x86_64.bash
          ./snowsql-1.2.23-linux_x86_64.bash --quiet -- -y || { echo "Installation failed"; exit 1; }

      - name: Validate SnowSQL Path
        run: |
          which snowsql || { echo "SnowSQL not found in PATH"; exit 1; }
          snowsql --version || { echo "SnowSQL execution failed"; exit 1; }

      - name: Test Snowflake Connection
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
          SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
          SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}
          SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
        run: |
          snowsql -a "$SNOWFLAKE_ACCOUNT" \
                  -u "$SNOWFLAKE_USER" \
                  -P "$SNOWFLAKE_PASSWORD" \
                  -d "$SNOWFLAKE_DATABASE" \
                  -s "$SNOWFLAKE_SCHEMA" \
                  -w "$SNOWFLAKE_WAREHOUSE" \
                  -q "SELECT CURRENT_VERSION();" || { echo "Query failed"; exit 2; }

      - name: Execute SQL Script
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
          SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
          SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}
          SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
        run: |
          snowsql -a "$SNOWFLAKE_ACCOUNT" \
                  -u "$SNOWFLAKE_USER" \
                  -P "$SNOWFLAKE_PASSWORD" \
                  -d "$SNOWFLAKE_DATABASE" \
                  -s "$SNOWFLAKE_SCHEMA" \
                  -w "$SNOWFLAKE_WAREHOUSE" \
                  -f code.sql || { echo "SQL script execution failed"; exit 2; }
