name: Deploy to Snowflake

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install SnowSQL
        run: |
          sudo apt update
          sudo apt install -y unzip
          
          # Download SnowSQL installation package
          curl -O https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/latest/linux_x86_64/snowsql-latest-linux_x86_64.bash

          # Install SnowSQL properly
          chmod +x snowsql-latest-linux_x86_64.bash
          ./snowsql-latest-linux_x86_64.bash --quiet -- -y

          # Ensure SnowSQL is in the PATH
          echo "/usr/bin" >> $GITHUB_PATH
          echo "export PATH=\$PATH:/usr/bin" >> ~/.bashrc
          echo "export PATH=\$PATH:/usr/bin" >> ~/.profile
          source ~/.bashrc
          source ~/.profile

      - name: Verify SnowSQL Installation
        run: |
          which snowsql
          ls -lah /usr/bin/snowsql
          file /usr/bin/snowsql
          snowsql --version

      - name: Debug Environment Variables
        run: |
          echo "SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}"
          echo "SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}"
          echo "SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}"
          echo "SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}"
          echo "SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}"
        shell: bash

      - name: Test Snowflake Connection
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
          SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
          SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}
          SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
        run: |
          snowsql --diag
          snowsql -a "$SNOWFLAKE_ACCOUNT" \
                  -u "$SNOWFLAKE_USER" \
                  -P "$SNOWFLAKE_PASSWORD" \
                  -d "$SNOWFLAKE_DATABASE" \
                  -s "$SNOWFLAKE_SCHEMA" \
                  -w "$SNOWFLAKE_WAREHOUSE" \
                  -q "SELECT CURRENT_VERSION();" || { echo "Query failed"; exit 2; }

      - name: Execute SQL Script
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
          SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
          SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}
          SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
        run: |
          snowsql -a "$SNOWFLAKE_ACCOUNT" \
                  -u "$SNOWFLAKE_USER" \
                  -P "$SNOWFLAKE_PASSWORD" \
                  -d "$SNOWFLAKE_DATABASE" \
                  -s "$SNOWFLAKE_SCHEMA" \
                  -w "$SNOWFLAKE_WAREHOUSE" \
                  -f code.sql || { echo "SQL script execution failed"; exit 2; }
